import Foundation
import HyperliquidSwift

/// Example demonstrating how to convert an account to multi-signature user
/// This corresponds to the Python example: basic_convert_to_multi_sig_user.py
class ConvertToMultiSigExample {
    
    static func main() async {
        do {
            // Setup client with testnet configuration
            let config = try ExampleUtils.loadConfig()
            let client = try await ExampleUtils.setupClient(config: config, useTestnet: true)
            
            // Important: Only the main wallet has permission to convert to multi-sig user
            // Agents do not have permission to perform this operation
            print("🔄 Converting account to multi-signature user...")
            
            // Authorized users are the public addresses of the wallets that will be able to sign
            // on behalf of the multi-sig user.
            // 
            // Important notes:
            // - Only existing users may be used (they must have deposited)
            // - The multi-sig signatures must be generated by the authorized user's wallet
            // - Agent/API wallets cannot be used for multi-sig signatures
            let authorizedUser1 = "0x0000000000000000000000000000000000000000"
            let authorizedUser2 = "0x0000000000000000000000000000000000000001"
            let threshold = 1 // Number of signatures required
            
            let result = try await client.convertToMultiSigUser(
                authorizedUsers: [authorizedUser1, authorizedUser2],
                threshold: threshold
            )
            
            print("✅ Multi-sig conversion result:")
            print(result)
            
            // After conversion, the account will require multi-signature for all operations
            print("📝 Account is now a multi-signature user requiring \(threshold) signature(s)")
            
        } catch {
            print("❌ Error converting to multi-sig user: \(error)")
        }
    }
}

// MARK: - Usage Instructions
/*
 To run this example:
 
 1. Ensure you have a valid config.json file with your wallet configuration
 2. Make sure your account has sufficient permissions (main wallet, not agent)
 3. Verify that the authorized users are existing Hyperliquid users
 4. Run the example:
    ```
    swift run ConvertToMultiSigExample
    ```
 
 Note: This is a permanent operation that cannot be easily reversed.
 Only use this on testnet unless you fully understand the implications.
 */
