name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode (Swift 6.0 toolchain)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Build (library and examples)
        run: |
          swift build -v
          swift build -v --product BasicUsage
          swift build -v --product TradingExample
          swift build -v --product AdvancedTradingExample

      - name: Run tests
        run: swift test -v

